name: icebox
description: An app for keeping track of what's in your freezers and when things expire.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.7
  intl: ^0.17.0
  uuid: ^3.0.5
  datetime_picker_formfield: ^2.0.0
  provider: ^6.0.1
  package_info_plus: ^1.3.0
  sqflite: ^2.0.0+4
  flutter_typeahead: ^3.2.3
  google_fonts: ^2.1.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.12
  file_picker: ^4.2.7

dev_dependencies:
  test: ^1.17.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: false
  image_path: "dev_assets/images/ice-cubes.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - google_fonts/